import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { errorText, Field } from '../shared/AdminWorkspace';
import '../shared/AdminWorkspace.css';
export default function InquiryPage({purchase=false}){
 const [values,setValues]=useState({name:'',email:'',school:'',interest:purchase?'Subscription':'Demo',content:''}),[plans,setPlans]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState('');
 useEffect(()=>{axios.get('/api/public/plans').then(r=>setPlans(r.data.plans)).catch(()=>{});},[]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{setDone((await axios.post('/api/public/inquiries',values)).data.message);}catch(err){setError(errorText(err));}finally{setBusy(false);}}
 return <div className="workspace"><header className="platform-header"><Link to="/" className="text-2xl font-bold text-primary">ERPZO</Link><Link to="/login">Sign in</Link></header><main className="workspace-section"><div className="grid lg:grid-cols-2 gap-12 py-10"><section><p className="uppercase tracking-widest text-sm font-semibold">One workspace for your school</p><h1>{purchase?'Find the right plan for your school':'See ERPZO in action'}</h1><p className="text-lg mt-5">Bring students, teachers, attendance, exams and fee management together. Tell us about your school to arrange a demonstration or request onboarding.</p><ul className="space-y-4 mt-8"><li>✓ A separate, protected workspace for every school</li><li>✓ Web administration and teacher/student portals</li><li>✓ School records, reporting and support in one place</li></ul>{plans.length>0&&<div className="mt-8 space-y-3">{plans.map(p=><article key={p.id} className="workspace-card"><h2>{p.name}</h2><p>{new Intl.NumberFormat('en',{style:'currency',currency:p.currency}).format(p.priceMinor/100)} / {p.interval.toLowerCase()} · {p.studentLimit} students</p><button onClick={()=>setValues(v=>({...v,interest:p.name}))}>Ask about {p.name}</button></article>)}</div>}</section><section className="workspace-card"><h2>{purchase?'Request school onboarding':'Request a demonstration'}</h2><p>We do not collect card details on this form.</p>{error&&<p role="alert" className="workspace-error">{error}</p>}{done?<div role="status"><h2>Request received</h2><p>{done}</p><Link to="/">Back to home</Link></div>:<form onSubmit={submit}><div className="workspace-fields">{[{name:'name',label:'Your name',required:true},{name:'email',label:'Work email',type:'email',required:true},{name:'school',label:'School name',required:true},{name:'interest',label:'Interested in',required:true},{name:'content',label:'Tell us about your school',type:'textarea',required:true}].map(f=><Field key={f.name} field={f} value={values[f.name]} onChange={value=>setValues(v=>({...v,[f.name]:value}))}/>)}</div><button className="workspace-primary" disabled={busy}>{busy?'Submitting…':'Submit request'}</button></form>}</section></div></main></div>;
}
