import {useEffect,useState} from 'react';
import axios from 'axios';
import ReferenceDashboard,{DashboardPanel,DashboardIcon} from '../shared/ReferenceDashboard';
import {errorText} from '../shared/AdminWorkspace';
export default function AdminDashboard({onNavigate}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[period,setPeriod]=useState('Quarterly');
 useEffect(()=>{const controller=new AbortController();axios.get('/api/school/dashboard-stats',{signal:controller.signal}).then(r=>setData(r.data)).catch(e=>{if(!axios.isCancel(e))setError(errorText(e));});return()=>controller.abort();},[]);
 if(!data)return <p className="p-6" role={error?'alert':'status'}>{error||'Loading school dashboard…'}</p>;
 const d=data.dashboard;if(!d)return <p className="p-6" role="alert">Restart the API to load the updated dashboard.</p>;
 const f=d.financialPeriods[period],total=f.collected+f.outstanding,percent=total?Math.round(f.collected/total*100):0;
 const money=n=>new Intl.NumberFormat('en',{style:'currency',currency:data.currency,maximumFractionDigits:0}).format(n);
 const link=(label,dest,center=false)=><button className={`reference-link ${center?'center':''}`} onClick={()=>onNavigate(dest)}>{label}<DashboardIcon name="arrow_forward"/></button>;
 const days=data.subscription?Math.max(0,Math.ceil((new Date(data.subscription.endDate)-Date.now())/86400000)):null;
 return <ReferenceDashboard title="Welcome back, Administrator" subtitle={d.recorded?`School is running at ${d.attendanceRate}% attendance today`:'No attendance recorded today'} badge={data.subscription?.plan||data.school.plan||'School administration'} badgeDetail={days===null?'No active subscription':`Subscription expires in ${days} days`}
 metrics={[{label:'Total Students',value:d.totalStudents.toLocaleString(),caption:'Active students',badge:`+${d.newStudents} this month`,icon:'groups'},{label:'Total Teachers',value:d.totalTeachers.toLocaleString(),caption:'Active educators',icon:'co_present',tone:'blue'},{label:'Total Staff',value:d.totalStaff.toLocaleString(),caption:'Support personnel',icon:'badge',tone:'coral'},{label:'Active Classes',value:d.activeClasses.toLocaleString(),caption:'Classes and sections',icon:'class',tone:'cyan'}]}
 ringTitle="Today's Attendance" ringValue={d.attendanceRate} ringCaption={`${d.present} of ${d.recorded} recorded students checked in today.`} ringAction={link('View detailed report','Attendance',true)}
 financeTitle="Fee Collection Summary" financeControl={<div className="reference-periods">{['Monthly','Quarterly'].map(p=><button key={p} aria-pressed={period===p} onClick={()=>setPeriod(p)}>{p}</button>)}</div>}
 financeCards={[{label:'Collected',value:money(f.collected),icon:'account_balance_wallet',percent,caption:`${period} payments received`},{label:'Outstanding',value:money(f.outstanding),icon:'pending_actions',percent:total?100-percent:0,tone:'negative',caption:'All unpaid fees in school currency'}]}
 actions={[['Create Announcement','campaign','Notifications'],['Add Student','person_add_alt','Student Management'],['Add Teacher','school','Teacher Management'],['Mark Attendance','how_to_reg','Attendance']].map(([label,icon,dest])=>({label,icon,onClick:()=>onNavigate(dest)}))} onChat={()=>onNavigate('Platform Support')}>
 <DashboardPanel title="Upcoming Exams" action={link('View all','Exam Management')}><div className="reference-list">{data.upcomingExams.length?data.upcomingExams.slice(0,3).map(e=><div key={e.id} className="reference-entry reference-exam"><div className="reference-date">{new Date(e.startDate).toLocaleDateString('en',{month:'short'})}<strong>{new Date(e.startDate).getDate()}</strong></div><div><strong>{e.name}</strong><p>{e.type} · {e.status}</p></div></div>):<p className="reference-empty">No upcoming exams scheduled.</p>}</div></DashboardPanel>
 <DashboardPanel title="Recent Admissions" action={link('See all','Student Management')}><div className="reference-list">{d.recentAdmissions.length?d.recentAdmissions.map(s=><div className="reference-entry" key={s.id}><span className="reference-avatar">{s.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div><strong>{s.name}</strong><p>{s.class?.name||'Class not assigned'} · Joined {new Date(s.createdAt).toLocaleDateString()}</p></div></div>):<p className="reference-empty">No students enrolled yet.</p>}</div></DashboardPanel>
 <DashboardPanel title="Announcements" action={<button className="reference-link" aria-label="Create announcement" onClick={()=>onNavigate('Notifications')}><DashboardIcon name="add"/></button>}><div className="reference-list">{data.recentActivities.length?data.recentActivities.slice(0,3).map((n,i)=><div className="reference-entry reference-note" key={i}><div><strong>{n.title}</strong><p>{n.desc}</p><p>{n.time}</p></div></div>):<p className="reference-empty">No announcements yet.</p>}</div></DashboardPanel>
 </ReferenceDashboard>;
}
