import { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { downloadBlob, errorText } from '../shared/AdminWorkspace';
import '../shared/AdminWorkspace.css';
export default function DocumentsView(){
  const [data,setData]=useState({documents:[],total:0,sizeBytes:0}),[file,setFile]=useState(null),[category,setCategory]=useState('General'),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=useCallback(async()=>{setBusy(true);try{setData((await axios.get('/api/school-admin/documents',{params:{page,search:query}})).data);setError('');}catch(e){setError(errorText(e));}finally{setBusy(false);}},[page,query]);
  useEffect(()=>{load();},[load]);
  async function upload(e){e.preventDefault();if(!file)return;const form=e.currentTarget;setBusy(true);try{const body=new FormData();body.append('file',file);body.append('category',category);await axios.post('/api/school-admin/documents',body);setFile(null);form.reset();await load();}catch(err){setError(errorText(err));}finally{setBusy(false);}}
  async function download(doc){try{const response=await axios.get(`/api/school-admin/documents/${doc.id}/download`,{responseType:'blob'});downloadBlob(response.data,doc.fileName);}catch(e){setError(errorText(e));}}
  async function remove(doc){if(!window.confirm(`Delete ${doc.name}?`))return;setBusy(true);try{await axios.delete(`/api/school-admin/documents/${doc.id}`);await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <section className="workspace-section"><h1>Document Management</h1><p>School-only document storage · up to 10 MB per file.</p>{error&&<p role="alert" className="workspace-error">{error}</p>}<form onSubmit={upload} className="workspace-card workspace-toolbar"><label>Document <input aria-label="Document file" type="file" required accept=".pdf,.png,.jpg,.jpeg,.txt,.csv,.docx,.xlsx" onChange={e=>setFile(e.target.files[0])}/></label><label>Category <select className="workspace-input" value={category} onChange={e=>setCategory(e.target.value)}>{['General','Policy','Student Record','Finance','HR','Compliance'].map(c=><option key={c}>{c}</option>)}</select></label><button className="workspace-primary" disabled={busy||!file}>Upload document</button></form><form className="workspace-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search);}}><input aria-label="Search documents" className="workspace-input" placeholder="Search documents…" value={search} onChange={e=>setSearch(e.target.value)}/><button>Search</button><span>{data.total} files · {(data.sizeBytes/1024/1024).toFixed(2)} MB stored</span></form>{busy&&<p role="status">Working…</p>}<div className="workspace-table"><table><thead><tr><th>Name</th><th>Category</th><th>Size</th><th>Uploaded by</th><th>Date</th><th>Actions</th></tr></thead><tbody>{data.documents.map(d=><tr key={d.id}><td>{d.name}</td><td>{d.category}</td><td>{(d.sizeBytes/1024).toFixed(1)} KB</td><td>{d.uploadedBy}</td><td>{new Date(d.createdAt).toLocaleDateString()}</td><td><div className="workspace-actions"><button onClick={()=>download(d)}>Download</button><button disabled={busy} onClick={()=>remove(d)}>Delete</button></div></td></tr>)}</tbody></table>{!data.documents.length&&!busy&&<p className="workspace-empty">No documents found.</p>}</div><div className="workspace-toolbar"><button disabled={page<=1||busy} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button disabled={page>=(data.totalPages||1)||busy} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>;
}
