import { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { FormDialog, errorText } from '../shared/AdminWorkspace';
const base = '/api/superadmin/tenants/schools';
const createFields = [{name:'name',label:'School name',required:true},{name:'slug',label:'School identifier (optional)'},{name:'adminName',label:'Administrator name',required:true},{name:'email',label:'Administrator email',type:'email',required:true},{name:'password',label:'Administrator password',type:'password',required:true},{name:'plan',label:'Plan label',default:'Free'}];
const editFields = [{name:'name',label:'School name',required:true},{name:'email',label:'Contact email',type:'email'},{name:'phone',label:'Phone'},{name:'address',label:'Address',type:'textarea'},{name:'subdomain',label:'Custom domain (optional)'},{name:'status',label:'Status',type:'select',options:['Active','Suspended']}];
export default function SchoolsWorkspace(){
  const [schools,setSchools]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[users,setUsers]=useState([]),[reset,setReset]=useState(null);
  const load=useCallback(async()=>{setBusy(true);try{setSchools((await axios.get(base)).data);setError('');}catch(e){setError(errorText(e));}finally{setBusy(false);}},[]);
  useEffect(()=>{load();},[load]);
  async function save(values){if(editing.id) await axios.put(`${base}/${editing.id}`,values);else await axios.post(base,values);await load();}
  async function details(school){setSelected(school);setUsers([]);setBusy(true);try{setUsers((await axios.get(`${base}/${school.id}/users`)).data);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <section className="workspace-section"><div className="workspace-heading"><div><h1>{selected ? selected.name : 'Manage Schools'}</h1><p>{selected ? 'School accounts and access management.' : 'Onboard schools with a working administrator account.'}</p></div><button className="workspace-primary" onClick={()=>setEditing({})}>Onboard school</button></div>
    {error && <p role="alert" className="workspace-error">{error}</p>}{busy && <p role="status">Loading…</p>}
    {selected ? <><button onClick={()=>setSelected(null)}>Back to schools</button><div className="workspace-stats">{Object.entries(selected._count).map(([label,value])=><div key={label} className="workspace-card workspace-stat"><span>{label}</span><strong>{value}</strong></div>)}</div><div className="workspace-table"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Last login</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name || '—'}</td><td>{u.email}</td><td>{u.role}</td><td>{u.lastLoginAt ? new Date(u.lastLoginAt).toLocaleString() : 'Never'}</td><td>{u.role !== 'SuperAdmin' && <button onClick={()=>setReset(u)}>Reset password</button>}</td></tr>)}</tbody></table></div></> : <><div className="workspace-toolbar"><input className="workspace-input" aria-label="Search schools" placeholder="Search school name or identifier…" value={search} onChange={e=>setSearch(e.target.value)} /><button onClick={load}>Refresh</button><span>{schools.length} schools</span></div><div className="workspace-table"><table><thead><tr><th>School</th><th>Identifier</th><th>Plan</th><th>Students</th><th>Status</th><th>Actions</th></tr></thead><tbody>{schools.filter(s=>(s.name+' '+s.slug).toLowerCase().includes(search.toLowerCase())).map(s=><tr key={s.id}><td>{s.name}</td><td>{s.slug}</td><td>{s.subscription?.plan.name || s.plan}</td><td>{s.students}</td><td>{s.status}</td><td><div className="workspace-actions"><button onClick={()=>details(s)}>View accounts</button><button onClick={()=>setEditing({...s,subdomain:s.domain || ''})}>Edit</button></div></td></tr>)}</tbody></table>{!busy && schools.length===0 && <p className="workspace-empty">No schools yet. Onboard your first school to get started.</p>}</div></>}
    {editing && <FormDialog title={editing.id?'Edit school':'Onboard school'} fields={editing.id?editFields:createFields} initial={editing} onSave={save} onClose={()=>setEditing(null)} />}
    {reset && <FormDialog title={`Reset password for ${reset.email}`} fields={[{name:'newPassword',label:'New password',type:'password',required:true}]} onSave={values=>axios.post(`${base}/${selected.id}/users/${reset.id}/reset-password`,values)} onClose={()=>setReset(null)} />}
  </section>;
}
