const prisma=require('../prismaClient');
async function schoolAnalytics(schoolId){
 const today=new Date();today.setHours(0,0,0,0);const tomorrow=new Date(today);tomorrow.setDate(tomorrow.getDate()+1);
 const startMonth=new Date(today.getFullYear(),today.getMonth(),1), sixMonths=new Date(today.getFullYear(),today.getMonth()-5,1), week=new Date(today);week.setDate(week.getDate()-6);
 const [school,totalStudents,totalTeachers,newStudents,newTeachers,attendance,payments,classes,notices,events,exams,totalStaff,recentAdmissions]=await Promise.all([
  prisma.school.findUniqueOrThrow({where:{id:schoolId},include:{subscription:{include:{plan:true}},settings:true}}),
  prisma.student.count({where:{schoolId,status:'Active'}}),prisma.teacher.count({where:{schoolId}}),prisma.student.count({where:{schoolId,createdAt:{gte:startMonth}}}),prisma.teacher.count({where:{schoolId,createdAt:{gte:startMonth}}}),
  prisma.attendance.findMany({where:{schoolId,date:{gte:week,lt:tomorrow}},select:{date:true,classId:true,status:true}}),prisma.feePayment.findMany({where:{schoolId},select:{amount:true,currency:true,status:true,paidDate:true,createdAt:true}}),
  prisma.class.findMany({where:{schoolId},include:{_count:{select:{students:true}}}}),prisma.notice.findMany({where:{schoolId},orderBy:{date:'desc'},take:5}),prisma.event.findMany({where:{schoolId,date:{gte:today}},orderBy:{date:'asc'},take:4}),prisma.exam.findMany({where:{schoolId,endDate:{gte:today}},orderBy:{startDate:'asc'},take:4}),prisma.staff.count({where:{schoolId}}),prisma.student.findMany({where:{schoolId},orderBy:{createdAt:'desc'},take:3,select:{id:true,name:true,createdAt:true,class:{select:{name:true}}}})
 ]);
 const todayAttendance=attendance.filter(a=>a.date>=today),present=todayAttendance.filter(a=>['Present','Late'].includes(a.status)).length;
 const rate=todayAttendance.length?Math.round(present/todayAttendance.length*1000)/10:0;
 const totals=new Map();for(const p of payments.filter(p=>p.status==='Paid'))totals.set(p.currency,(totals.get(p.currency)||0)+p.amount);
 const collected=[...totals].map(([currency,amount])=>new Intl.NumberFormat('en',{style:'currency',currency}).format(amount)).join(' / ')||'0';
 const recentActivities=notices.map(n=>({title:n.title,desc:n.content.slice(0,100),time:new Date(n.date).toLocaleDateString()}));
 const topClasses=classes.map(c=>{const rows=todayAttendance.filter(a=>a.classId===c.id);return {name:c.name,students:c._count.students,attendance:rows.length?Math.round(rows.filter(a=>['Present','Late'].includes(a.status)).length/rows.length*100):0};}).sort((a,b)=>b.attendance-a.attendance).slice(0,4);
 const revenueData=Array.from({length:6},(_,i)=>{const start=new Date(sixMonths.getFullYear(),sixMonths.getMonth()+i,1),end=new Date(start.getFullYear(),start.getMonth()+1,1);return {label:start.toLocaleDateString('en',{month:'short'}),value:payments.filter(p=>p.status==='Paid'&&p.currency===school.paymentCurrency&&p.paidDate>=start&&p.paidDate<end).reduce((sum,p)=>sum+p.amount,0)};});
 const attendanceData=Array.from({length:7},(_,i)=>{const start=new Date(week);start.setDate(start.getDate()+i);const end=new Date(start);end.setDate(end.getDate()+1);const rows=attendance.filter(a=>a.date>=start&&a.date<end);return {label:start.toLocaleDateString('en',{weekday:'short'}),value:rows.length?Math.round(rows.filter(a=>['Present','Late'].includes(a.status)).length/rows.length*100):0};});
 const financialPeriods=Object.fromEntries(['Monthly','Quarterly'].map(period=>{const start=new Date(today.getFullYear(),period==='Monthly'?today.getMonth():Math.floor(today.getMonth()/3)*3,1);const end=new Date(start.getFullYear(),start.getMonth()+(period==='Monthly'?1:3),1);const rows=payments.filter(p=>p.currency===school.paymentCurrency);return [period,{collected:rows.filter(p=>p.status==='Paid'&&p.paidDate>=start&&p.paidDate<end).reduce((sum,p)=>sum+p.amount,0),outstanding:rows.filter(p=>['Pending','Overdue'].includes(p.status)).reduce((sum,p)=>sum+p.amount,0)}];}));
 return {dashboard:{totalStudents,totalTeachers,totalStaff,activeClasses:classes.length,newStudents,attendanceRate:rate,present,recorded:todayAttendance.length,recentAdmissions,financialPeriods},stats:[{label:'Total Students',value:String(totalStudents),change:String(newStudents),changeLabel:'admitted this month',icon:'groups',color:'#006b5c'},{label:'Total Teachers',value:String(totalTeachers),change:String(newTeachers),changeLabel:'added this month',icon:'badge',color:'#0060ac'},{label:'Attendance Rate',value:`${rate}%`,changeLabel:todayAttendance.length?'recorded attendance today':'no attendance recorded today',icon:'trending_up',color:'#006b5c'},{label:'Fee Collection',value:collected,change:'',changeLabel:'settled payments',icon:'payments',color:'#9d4224'}],recentActivities,topClasses,upcomingEvents:events.map(e=>({...e,date:String(e.date.getDate()).padStart(2,'0'),month:e.date.toLocaleDateString('en',{month:'short'})})),upcomingExams:exams,subscription:school.subscription?{plan:school.subscription.plan.name,status:school.subscription.status,endDate:school.subscription.endDate}:null,school:{name:school.name,plan:school.plan},revenueData,attendanceData,currency:school.paymentCurrency,generatedAt:new Date()};
}
module.exports={schoolAnalytics};
